version: '3.7'

services:

  bot:
    container_name: pingbot
    image: pingbot
    restart: always
    environment:
      BOT_ENV: |
        botid: 123456789:abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
        userid: 123456789
        hosts:
          - "8.8.8.8:Google DNS"
          - "77.88.8.8:Yandex DNS"